#!/usr/bin/env bash
# Nginx installation 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
l="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $l" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
