#!/bin/bash
i=0

while [ $i -lt 9 ]
do
  echo "Best School"
  ((i++))
  if [[ "$i" -eq '3' ]]; then
    echo "bad luck"
  elif [[ "$i" -eq '7' ]]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
