#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
i=0
while [ $i -le 12 ]
do
    m=1
    echo "Hour: $i"
    while [ $m -le 59 ]
    do
        echo "$m"
        ((m++))
    done
    ((i++)) 
done
